apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend-studio
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: client-values
    files:
      - values.yaml=../../config/client.yaml
  - name: studio-product-values
    files:
      - values.yaml=values.yaml
