apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth-keycloak-api-key-bridge
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: client-values
    files:
      - values.yaml=../../config/client.yaml
  - name: keycloak-api-key-bridge-product-values
    files:
      - values.yaml=values.yaml
