apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m
  path: ./releases/applications
  timeout: 120m
  wait: true
  healthCheckExprs:
    - apiVersion: gateway.networking.k8s.io/v1
      kind: Gateway
      inProgress: '!status.conditions.exists(e, e.type == ''Programmed'' && e.observedGeneration == metadata.generation) || status.listeners.size() != spec.listeners.size() || status.listeners.exists(l, !l.conditions.exists(e, e.type == ''ResolvedRefs'' && e.observedGeneration == metadata.generation)) || status.listeners.exists(l, l.conditions.exists(e, e.type == ''ResolvedRefs'' && e.observedGeneration == metadata.generation && e.status == ''False'' && e.reason == ''InvalidCertificateRef''))'
      failed: 'status.listeners.exists(l, l.conditions.exists(e, e.type == ''ResolvedRefs'' && e.observedGeneration == metadata.generation && e.status == ''False'' && e.reason == ''RefNotPermitted''))'
      current: 'status.conditions.exists(e, e.type == ''Programmed'' && e.observedGeneration == metadata.generation && e.status == ''True'') && status.listeners.size() == spec.listeners.size() && status.listeners.all(l, l.conditions.exists(e, e.type == ''ResolvedRefs'' && e.observedGeneration == metadata.generation && e.status == ''True''))'
  prune: true
  dependsOn:
    - name: infrastructure
    - name: client-app-values
  sourceRef:
    kind: GitRepository
    name: k8s-stack
    namespace: flux-system
