apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-identity.yaml
  - platform-source.yaml
  - namespaces.yaml
  - client-values.yaml
  - infrastructure.yaml
  - applications.yaml
  - flux-system
