apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infra-agentgateway
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: client-values
    files:
      - values.yaml=../../../config/client.yaml
  - name: agentgateway-product-values
    files:
      - values.yaml=values.yaml
  - name: client-openrouter-catalog-values
    files:
      - values.yaml=../../../config/openrouter-catalog.yaml
  - name: client-model-cost-catalog
    files:
      - catalog.json=model-pricing.json
